version: '3'

services:
  api-server:
    build: ./
    entrypoint: ['npm', 'run', 'dev']
    env_file: ./debby-hand-knits/config/config.env
    ports:
      - '3000:3000'
    networks:
      - debby-hand-knits-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    # image: mongo:3.6-xenial
    image: mongo:4.0.25-xenial
    environment:
      - MONGO_INITDB_DATABASE=debby-hand-knits
    ports:
      - '27017:27017'
    networks:
      - debby-hand-knits-app
    volumes:
      - mongo-data:/data/db

networks:
  debby-hand-knits-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
