version: '3'

services:
  user:
    build:
      context: .
    ports:
      - 8082:5000
    volumes:
      - ./app:/app
    depends_on:
      - user_db
    restart: always
    networks:
      - user-network

  user_db:
    # image: mysql:5.7.22
    image: mysql:5.7.34
    volumes:
      - user-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=user
    restart: always
    networks:
      - user-network

volumes:
  user-db-data:

networks:
  user-network:
    driver: bridge