version: '3'

services:
  order:
    build:
      context: .
    ports:
      - 80:5000
    volumes:
      - ./app:/app
    links:
      - order_db
    depends_on:
      - order_db

  order_db:
    # image: mysql:5.7.22
    image: mysql:5.7.34
    volumes:
      - product-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=order
    restart: always

volumes:
  order-db-data:
    