version: '3'

services:
  product:
    build:
      context: .
    ports:
      - 80:5000
    links:
      - product_db
    depends_on:
      - product_db

  product_db:
    # image: mysql:5.7.22
    image: mysql:5.7.34
    volumes:
      - product-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=product
    restart: always

volumes:
  product-db-data:
